name: Test Workflow

on:
  push:
    branches:
      - main  # Déclenche le workflow lors d'un push vers la branche 'main'

jobs:
  test:
    runs-on: ubuntu-latest  # Utilise un environnement Ubuntu

    steps:
      - name: Checkout code
        uses: actions/checkout@v2  # Récupère ton code

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'  # Installe Python 3.8

      - name: Run the test
        run: python test.py  # Exécute le script Python

